/*
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ZPB4', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ZPB3', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ZPB2', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ZPB1', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ADB1', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('KIB1C', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('KIB1A', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('FTB1', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('EBO32', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ABR 016', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('VNB 1A', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('GMB 1A', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('CARDCOMMANDER', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('PRESSOSTATO', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ANALOGICO. A161', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ANALOGICO. A163', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('ANALOGICO. A167', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA04_A161', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA04_A163', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA04_A167', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA05_A161', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA05_A163', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('SCA05_A167', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('LENZE(TC) 0,25kw', 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');
    INSERT INTO `placas_wentex` (`nomePlaca`,`quantidade`,`situacao`, `local`, `qtdParaSituacaoBaixa` , `qtdParaSituacaoOk`, `regUltimaEdicao`, `fotoUltimoUser`) VALUES ('LENZE(TC) 0,37kw' , 2 , 'Ok', 'Cardas','4','2', '70297', 'NULL');

    */